# create your drupal and postgres config here, based off the last assignment
version: '2'

services:

    # "drupal" here is the service name, which is also used as the DNS name.
  drupal:
    image: custom-drupal:8.8.2
    # this "." dot at build indicates that the dockerfile exists in the same directory as this compose file
    build: .
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres:12.1
    environment:
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
    drupal-data: